### ISSUE TITLE
three buttons not came in same line share button goes down

### ISSUE THREAD

**Issue by vidhya199** [ionic-team/ionic-preview-app#119]
help me

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm going to close this as it doesn't seem like it's an issue with the preview app itself. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

If this is an issue with the preview app, please provide more information in order for us to reproduce the issue.

Thanks so much!
