### ISSUE TITLE
Why navigation push actions are performed modally?

### ISSUE THREAD

**Issue by tianchan2017** [ionic-team/ionic-preview-app#120]

**Comment by janpio** [comment]
What exactly is your question? I don't understand what you mean with that subject. Please elaborate.

**Comment by tianchan2017** [comment]
Former times I have done several ios projects.
I'm new trainer of ionic, so I followed ionic tutorials.
When I execute navigation component, my result isn't like sample's result.
I wanted push effect but it shows modal effect.
I would be very grateful if you could give me a reason.

**Comment by janpio** [comment]
This doesn't sound like an issue, but a (community) support request. Please open a topic at https://forum.ionicframework.com/ and post a link to it here and then close this issue. Thank.

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm going to close this as it doesn't seem like it's an issue with the preview app itself. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

If this is an issue with the preview app, please provide more information in order for us to reproduce the issue.

Thanks so much!
