### ISSUE TITLE
how to save date in a our given format?

### ISSUE THREAD

**Issue by chan51** [ionic-team/ionic-preview-app#121]
How to save date from Date Picker in our own format. Date Picker only saving date in YYYY-MM-DD format.
Can anyone help me on this?

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm going to close this as it doesn't seem like it's an issue with the preview app itself. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

If this is an issue with the preview app, please provide more information in order for us to reproduce the issue.

Thanks so much!
