### ISSUE TITLE
Runtime Error: No component factory found for PopoverPage

### ISSUE THREAD

**Issue by Ezerbg** [ionic-team/ionic-preview-app#122]
**This error is shown while testing the popover with computer browser**
-----------------------------------------------------------------------------------
Runtime Error
Uncaught (in promise): Error: No component factory found for PopoverPage. Did you add it to @NgModule.entryComponents? Error: No component factory found for PopoverPage. Did you add it to @NgModule.entryComponents? at noComponentFactoryError (http://localhost:8100/build/main.js:3683:34) at _NullComponentFactoryResolver.resolveComponentFactory (http://localhost:8100/build/main.js:3701:15) at CodegenComponentFactoryResolver.resolveComponentFactory (http://localhost:8100/build/main.js:3743:87) at PopoverCmp._load (http://localhost:8100/build/main.js:50894:57) at PopoverCmp.ionViewPreLoad (http://localhost:8100/build/main.js:50882:14) at PopoverImpl.ViewController._lifecycle (http://localhost:8100/build/main.js:17327:33) at PopoverImpl.ViewController._preLoad (http://localhost:8100/build/main.js:17177:14) at OverlayPortal.NavControllerBase._preLoad (http://localhost:8100/build/main.js:44833:14) at OverlayPortal.NavControllerBase._viewInit (http://localhost:8100/build/main.js:44477:14) at http://localhost:8100/build/main.js:44267:23

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm going to close this as it doesn't seem like it's an issue with the preview app itself. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

If this is an issue with the preview app, please provide more information in order for us to reproduce the issue.

Thanks so much!
