### ISSUE TITLE
How to implement the nested segment

### ISSUE THREAD

**Issue by tomNjerry** [ionic-team/ionic-preview-app#128]
How to prevent data of child segment to not being display to parent segments having 
![screenshot_2017-09-08-22-54-16](https://user-images.githubusercontent.com/17373795/30223686-82f602ea-94e9-11e7-9448-79c4efa539c8.png)
![screenshot_2017-09-08-22-54-01](https://user-images.githubusercontent.com/17373795/30223687-82f83cfe-94e9-11e7-8636-5601a36bdec2.png)
![screenshot_2017-09-08-22-53-24](https://user-images.githubusercontent.com/17373795/30223685-82f35874-94e9-11e7-95b0-9f321af652de.png)

same level

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm going to close this as it doesn't seem like it's an issue with the preview app itself. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

If this is an issue with the preview app, please provide more information in order for us to reproduce the issue.

Thanks so much!
