### ISSUE TITLE
Modal Controller instance member "config"

### ISSUE THREAD

**Issue by Simplelenz** [ionic-team/ionic-preview-app#129]
Hello

What are the options for "config" in Modal Controller? Is there any documentation on this? Thanks

**Comment by brandyscarney** [comment]
Thanks for the issue! The config is our Config object: http://ionicframework.com/docs/api/config/Config/ 

It is a reference to the global config, and is not meant to be changed when creating a modal. This needs to be hidden from the docs. 

I'm going to close this as it isn't an issue with the preview app itself. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

Thanks so much!
