### ISSUE TITLE
ion-footer hides content

### ISSUE THREAD

**Issue by Malvika21** [ionic-team/ionic-preview-app#130]
<ion-content>

      <ion-list>
        <ng-container *ngFor="let p of pages">
          <button menuClose ion-item (click)="openPage(p)" *ngIf="!p.hidden">
            {{p.title}}
          </button>
        </ng-container>

      </ion-list>
      <ion-footer>
        <ion-toolbar>
          <ion-title>
            <span style=>app version: {{currentuserAppversion}}</span>
          </ion-title>
        </ion-toolbar>
      </ion-footer>
    </ion-content>

<ion-footer> is hiding the navigation content

**Comment by brandyscarney** [comment]
The footer component should be placed at the root of a page, alongside `ion-content`. So it shouldn't be inside of `ion-content` in order for content to calculate its size properly:

```
<ion-header>
  ...
</ion-header>
<ion-content>
  ...
</ion-content>
<ion-footer>
  ...
</ion-footer>
```

I'm going to close this as it isn't an issue with the preview app itself. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

If this is an issue with the preview app, please provide more information in order for us to reproduce the issue.

Thanks so much!
