### ISSUE TITLE
Ionic not building correctly in Visual Studio 2017

### ISSUE THREAD

**Issue by SpotOnCreative** [ionic-team/ionic-preview-app#133]
Hello. When I run `ionic build` and then `cordova run android` in the command prompt, I'm able to view my app fine on my phone. Whereas, when I use Visual Studio 2017 Community Edition to build and serve my ionic app, it is unable to copy the three following files to the build folder:

`main.js`
`vendor.js`
`main.css`

Ionic Information
cli packages: (C:\Users\tweez\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : not installed

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 5.2.2 ios 4.2.1
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v6.11.2
    npm  : 3.10.10
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy

Any ideas what is causing this issue?

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm going to close this as it doesn't seem like it's an issue with the preview app itself. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

Thanks so much!
