### ISSUE TITLE
Buttons In Components doesn't work properly , both are displaying at right corner

### ISSUE THREAD

**Issue by lsaballo** [ionic-team/ionic-preview-app#134]
<ion-header>
  <ion-navbar>
    <ion-buttons start>
      <button ion-button icon-only>
        <ion-icon name="contact"></ion-icon>
      </button>
    </ion-buttons>

    <ion-buttons end>
      <button ion-button icon-only>
        <ion-icon name="search"></ion-icon>
      </button>
    </ion-buttons>
  </ion-navbar>
</ion-header>

**Comment by mhartington** [comment]
Hey there! So it looks like your issue is not related to the preview app, but rather a framework question/issue. Please open an issue on the ionic repo

https://github.com/driftyco/ionic
