### ISSUE TITLE
How to set cssClass

### ISSUE THREAD

**Issue by controlrole** [ionic-team/ionic-preview-app#136]
hello,
How to set cssClass?

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm going to close this as it doesn't seem like it's an issue with the preview app itself. Please visit our [documentation](https://ionicframework.com/docs/), [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

If this is an issue with the preview app, please provide more information in order for us to reproduce the issue.

Thanks so much!
